# Generated by Django 6.0.5 on 2026-05-15 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['workspace', 'user'], name='workspaces__workspa_02f6dd_idx'),
        ),
    ]
