# Generated by Django 6.0.5 on 2026-05-15 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_member_workspaces__workspa_02f6dd_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent')], db_index=True, default='agent', max_length=16)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('accepted', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'convite de workspace',
                'verbose_name_plural': 'convites de workspace',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'email'], name='workspaces__workspa_6d2690_idx')],
            },
        ),
    ]
