# Generated by Django 6.0.5 on 2026-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspaceinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='ai_system_prompt',
            field=models.TextField(blank=True, help_text='Prompt de sistema que define a personalidade e as regras do assistente de IA para este workspace.', null=True),
        ),
    ]
