# Generated by Django 6.0.5 on 2026-07-04 15:10

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_workspace_ai_system_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('openai_api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('system_prompt', models.TextField(default='Você é um assistente virtual prestativo. Seja conciso.')),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=64)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'configuracao de IA do workspace',
                'verbose_name_plural': 'configuracoes de IA dos workspaces',
            },
        ),
    ]
