# Generated by Django 6.0.5 on 2026-07-07 13:23

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import connection, migrations, models


def copy_legacy_openai_configs(apps, schema_editor):
    """Copia a configuracao OpenAI legada para o novo modelo generico."""
    WorkspaceAIConfig = apps.get_model('workspaces', 'WorkspaceAIConfig')
    WorkspaceAIProviderConfig = apps.get_model('workspaces', 'WorkspaceAIProviderConfig')
    db_alias = schema_editor.connection.alias if schema_editor is not None else connection.alias

    for legacy_config in WorkspaceAIConfig.objects.using(db_alias).all():
        WorkspaceAIProviderConfig.objects.using(db_alias).update_or_create(
            workspace_id=legacy_config.workspace_id,
            provider='openai',
            defaults={
                'api_key': legacy_config.openai_api_key or '',
                'model_name': legacy_config.model_name or 'gpt-4o-mini',
                'system_prompt': legacy_config.system_prompt or '',
                'is_active': legacy_config.is_active,
                'settings': {},
            },
        )


def reverse_legacy_openai_configs(apps, schema_editor):
    """Restaura configs OpenAI para o modelo legado em rollback."""
    WorkspaceAIConfig = apps.get_model('workspaces', 'WorkspaceAIConfig')
    WorkspaceAIProviderConfig = apps.get_model('workspaces', 'WorkspaceAIProviderConfig')
    db_alias = schema_editor.connection.alias if schema_editor is not None else connection.alias

    for provider_config in WorkspaceAIProviderConfig.objects.using(db_alias).filter(provider='openai'):
        WorkspaceAIConfig.objects.using(db_alias).update_or_create(
            workspace_id=provider_config.workspace_id,
            defaults={
                'openai_api_key': provider_config.api_key,
                'model_name': provider_config.model_name or 'gpt-4o-mini',
                'system_prompt': provider_config.system_prompt or '',
                'is_active': provider_config.is_active,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspaceaiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('google', 'Google Gemini')], db_index=True, max_length=32)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('model_name', models.CharField(max_length=128)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_configs', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'configuracao de provedor de IA do workspace',
                'verbose_name_plural': 'configuracoes de provedores de IA dos workspaces',
                'ordering': ('workspace', 'provider'),
                'constraints': [models.UniqueConstraint(fields=('workspace', 'provider'), name='unique_ai_provider_per_workspace'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('workspace',), name='unique_active_ai_provider_per_workspace')],
            },
        ),
        migrations.RunPython(
            copy_legacy_openai_configs,
            reverse_legacy_openai_configs,
        ),
    ]
