# Generated by Django 6.0.5 on 2026-07-07 15:43

from django.db import migrations, models


def _select_provider_config(provider_configs, workspace_id):
    provider_config = (
        provider_configs.filter(
            workspace_id=workspace_id,
            is_active=True,
        )
        .order_by('provider')
        .first()
    )
    if provider_config is not None:
        return provider_config

    return (
        provider_configs.filter(
            workspace_id=workspace_id,
            provider='openai',
        )
        .order_by('created_at')
        .first()
    )


def copy_workspace_prompt_to_provider_config(apps, schema_editor):
    Workspace = apps.get_model('workspaces', 'Workspace')
    WorkspaceAIProviderConfig = apps.get_model('workspaces', 'WorkspaceAIProviderConfig')
    db_alias = schema_editor.connection.alias

    workspaces = (
        Workspace.objects.using(db_alias)
        .exclude(ai_system_prompt__isnull=True)
        .exclude(ai_system_prompt='')
        .only('id', 'ai_system_prompt')
    )
    provider_configs = WorkspaceAIProviderConfig.objects.using(db_alias)

    for workspace in workspaces:
        provider_config = _select_provider_config(provider_configs, workspace.id)
        if provider_config is None or provider_config.system_prompt:
            continue

        provider_config.system_prompt = workspace.ai_system_prompt
        provider_config.save(update_fields=['system_prompt'])


def reverse_workspace_prompt_from_provider_config(apps, schema_editor):
    Workspace = apps.get_model('workspaces', 'Workspace')
    WorkspaceAIProviderConfig = apps.get_model('workspaces', 'WorkspaceAIProviderConfig')
    db_alias = schema_editor.connection.alias

    workspaces = Workspace.objects.using(db_alias).filter(
        models.Q(ai_system_prompt__isnull=True) | models.Q(ai_system_prompt=''),
    )
    provider_configs = WorkspaceAIProviderConfig.objects.using(db_alias)

    for workspace in workspaces:
        provider_config = _select_provider_config(provider_configs, workspace.id)
        if provider_config is None or not provider_config.system_prompt:
            continue

        workspace.ai_system_prompt = provider_config.system_prompt
        workspace.save(update_fields=['ai_system_prompt'])


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_workspaceaiproviderconfig'),
    ]

    operations = [
        migrations.RunPython(
            copy_workspace_prompt_to_provider_config,
            reverse_workspace_prompt_from_provider_config,
        ),
    ]
