# Generated by Django 6.0.5 on 2026-06-30 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('workspaces', '0003_workspaceinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=16)),
                ('model_name', models.CharField(db_index=True, max_length=128)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='core_auditl_workspa_db0a47_idx'), models.Index(fields=['workspace', 'action'], name='core_auditl_workspa_98f7aa_idx'), models.Index(fields=['workspace', 'model_name'], name='core_auditl_workspa_1ded7b_idx')],
            },
        ),
    ]
