# Generated by Django 6.0.5 on 2026-05-25 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_contact_channel_id_contact_starred_lead_assigned_to_and_more'),
        ('workspaces', '0003_workspaceinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada'), ('pending', 'Pendente')], db_index=True, default='open', max_length=16)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='crm.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'conversa',
                'verbose_name_plural': 'conversas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('direction', models.CharField(choices=[('inbound', 'Entrada'), ('outbound', 'Saída')], db_index=True, max_length=16)),
                ('status', models.CharField(blank=True, choices=[('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], db_index=True, max_length=16, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='omnichannel.conversation')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace', 'status'], name='omnichannel_workspa_cb72de_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['contact', 'channel'], name='omnichannel_contact_155c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='omnichannel_convers_4d3595_idx'),
        ),
    ]
