# Generated by Django 6.0.5 on 2026-06-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnichannel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID da mensagem no provedor (ex.: wamid da Meta).', max_length=255, null=True),
        ),
    ]
