# Generated by Django 6.0.5 on 2026-06-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnichannel', '0002_message_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_human_handoff',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
