# Generated by Django 6.0.5 on 2026-07-13 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnichannel', '0003_conversation_is_human_handoff'),
        ('workspaces', '0007_consolidate_system_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Em processamento'), ('succeeded', 'Concluido'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], db_index=True, default='running', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processing_runs', to='omnichannel.conversation')),
                ('output_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_processing_output_run', to='omnichannel.message')),
                ('provider_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_processing_runs', to='workspaces.workspaceaiproviderconfig')),
                ('source_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processing_run', to='omnichannel.message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processing_runs', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'execucao de IA',
                'verbose_name_plural': 'execucoes de IA',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'status'], name='omnichannel_workspa_8b48b8_idx'), models.Index(fields=['conversation', 'status'], name='omnichannel_convers_e3a42e_idx'), models.Index(fields=['status', 'created_at'], name='omnichannel_status_c3ccf6_idx')],
            },
        ),
    ]
