# Generated by Django 6.0.5 on 2026-07-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnichannel', '0004_aiprocessingrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], db_index=True, max_length=16, null=True),
        ),
    ]
