# Generated by Django 6.0.5 on 2026-07-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnichannel', '0005_message_send_error_code_alter_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprocessingrun',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprocessingrun',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aiprocessingrun',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='last_send_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='next_send_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='send_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aiprocessingrun',
            name='status',
            field=models.CharField(choices=[('running', 'Em processamento'), ('retrying', 'Aguardando retry'), ('succeeded', 'Concluido'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], db_index=True, default='running', max_length=16),
        ),
    ]
