# Generated by Django 6.0.5 on 2026-07-14 19:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnichannel', '0006_aiprocessingrun_last_attempt_at_and_more'),
        ('workspaces', '0007_consolidate_system_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIObservabilityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('AI_SCHEDULED', 'AI scheduled'), ('AI_SKIPPED', 'AI skipped'), ('AI_PROVIDER_ATTEMPT', 'AI provider attempt'), ('AI_PROVIDER_SUCCESS', 'AI provider success'), ('AI_PROVIDER_RETRYING', 'AI provider retrying'), ('AI_PROVIDER_FAILED', 'AI provider failed'), ('OUTBOUND_DELIVERY_ATTEMPT', 'Outbound delivery attempt'), ('OUTBOUND_DELIVERY_SUCCESS', 'Outbound delivery success'), ('OUTBOUND_DELIVERY_RETRYING', 'Outbound delivery retrying'), ('OUTBOUND_DELIVERY_FAILED', 'Outbound delivery failed'), ('PROVIDER_TEST_SUCCESS', 'Provider test success'), ('PROVIDER_TEST_FAILED', 'Provider test failed'), ('PROVIDER_ACTIVATED', 'Provider activated'), ('PROVIDER_DEACTIVATED', 'Provider deactivated'), ('CREDENTIAL_REPLACED', 'Credential replaced'), ('CREDENTIAL_REPLACE_FAILED', 'Credential replace failed'), ('CREDENTIAL_REVOKED', 'Credential revoked')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('retrying', 'Retrying'), ('pending', 'Pending')], db_index=True, max_length=32)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ai_processing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observability_events', to='omnichannel.aiprocessingrun')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_observability_events', to='omnichannel.conversation')),
                ('output_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_observability_events', to='omnichannel.message')),
                ('provider_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observability_events', to='workspaces.workspaceaiproviderconfig')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_observability_events', to='omnichannel.message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_observability_events', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'evento de observabilidade de IA',
                'verbose_name_plural': 'eventos de observabilidade de IA',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='omnichannel_workspa_c6a456_idx'), models.Index(fields=['workspace', 'event_type', 'created_at'], name='omnichannel_workspa_42d6e2_idx'), models.Index(fields=['workspace', 'status', 'created_at'], name='omnichannel_workspa_542038_idx'), models.Index(fields=['workspace', 'provider', 'created_at'], name='omnichannel_workspa_ec0112_idx'), models.Index(fields=['workspace', 'error_code', 'created_at'], name='omnichannel_workspa_2362a0_idx')],
            },
        ),
    ]
