# Generated by Django 6.0.5 on 2026-07-17 19:08

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnichannel', '0007_aiobservabilityevent'),
        ('workspaces', '0007_consolidate_system_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('evolution', 'Evolution API')], db_index=True, default='evolution', max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('instance_name', models.CharField(max_length=128, unique=True)),
                ('instance_id', models.CharField(blank=True, default='', max_length=255)),
                ('instance_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('webhook_public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('webhook_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('provisioning', 'Provisionando'), ('waiting_qr', 'Aguardando QR Code'), ('connecting', 'Conectando'), ('connected', 'Conectado'), ('reconnecting', 'Reconectando'), ('error', 'Erro'), ('deleting', 'Excluindo')], db_index=True, default='disconnected', max_length=32)),
                ('phone_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_connection_update_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=128)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_channels', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'canal WhatsApp',
                'verbose_name_plural': 'canais WhatsApp',
                'ordering': ('workspace', 'name'),
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='whatsapp_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='omnichannel.whatsappchannel'),
        ),
        migrations.AddIndex(
            model_name='whatsappchannel',
            index=models.Index(fields=['workspace', 'status'], name='omni_wa_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappchannel',
            index=models.Index(fields=['workspace', 'provider'], name='omni_wa_ws_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappchannel',
            index=models.Index(fields=['workspace', 'created_at'], name='omni_wa_ws_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappchannel',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='omni_wa_unique_ws_name'),
        ),
    ]
