# Generated by Django 6.0.5 on 2026-07-18 20:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnichannel', '0008_whatsappchannel_conversation_whatsapp_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=64)),
                ('deduplication_key', models.CharField(max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed')], default='PROCESSING', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'evento de webhook Evolution',
                'verbose_name_plural': 'eventos de webhook Evolution',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='message',
            name='provider_message_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_key__isnull', False)), fields=('provider_message_key',), name='omni_message_unique_provider_key'),
        ),
        migrations.AddField(
            model_name='evolutionwebhookevent',
            name='whatsapp_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_webhook_events', to='omnichannel.whatsappchannel'),
        ),
        migrations.AddIndex(
            model_name='evolutionwebhookevent',
            index=models.Index(fields=['whatsapp_channel', 'event_type'], name='omni_evo_channel_event_idx'),
        ),
        migrations.AddIndex(
            model_name='evolutionwebhookevent',
            index=models.Index(fields=['whatsapp_channel', 'status'], name='omni_evo_channel_status_idx'),
        ),
        migrations.AddIndex(
            model_name='evolutionwebhookevent',
            index=models.Index(fields=['external_id'], name='omni_evo_external_id_idx'),
        ),
        migrations.AddIndex(
            model_name='evolutionwebhookevent',
            index=models.Index(fields=['created_at'], name='omni_evo_created_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='evolutionwebhookevent',
            constraint=models.UniqueConstraint(fields=('whatsapp_channel', 'deduplication_key'), name='omni_evo_event_unique_channel_key'),
        ),
    ]
