# Generated by Django 6.0.5 on 2026-07-31 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnichannel', '0009_evolution_event_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiobservabilityevent',
            name='whatsapp_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observability_events', to='omnichannel.whatsappchannel'),
        ),
        migrations.AlterField(
            model_name='aiobservabilityevent',
            name='event_type',
            field=models.CharField(choices=[('AI_SCHEDULED', 'AI scheduled'), ('AI_SKIPPED', 'AI skipped'), ('AI_PROVIDER_ATTEMPT', 'AI provider attempt'), ('AI_PROVIDER_SUCCESS', 'AI provider success'), ('AI_PROVIDER_RETRYING', 'AI provider retrying'), ('AI_PROVIDER_FAILED', 'AI provider failed'), ('OUTBOUND_DELIVERY_ATTEMPT', 'Outbound delivery attempt'), ('OUTBOUND_DELIVERY_SUCCESS', 'Outbound delivery success'), ('OUTBOUND_DELIVERY_RETRYING', 'Outbound delivery retrying'), ('OUTBOUND_DELIVERY_FAILED', 'Outbound delivery failed'), ('PROVIDER_TEST_SUCCESS', 'Provider test success'), ('PROVIDER_TEST_FAILED', 'Provider test failed'), ('PROVIDER_ACTIVATED', 'Provider activated'), ('PROVIDER_DEACTIVATED', 'Provider deactivated'), ('CREDENTIAL_REPLACED', 'Credential replaced'), ('CREDENTIAL_REPLACE_FAILED', 'Credential replace failed'), ('CREDENTIAL_REVOKED', 'Credential revoked'), ('CHANNEL_CREATED', 'Channel created'), ('CHANNEL_PROVISIONED', 'Channel provisioned'), ('CHANNEL_WEBHOOK_CONFIGURED', 'Channel webhook configured'), ('CHANNEL_QR_GENERATED', 'Channel QR generated'), ('CHANNEL_CONNECTED', 'Channel connected'), ('CHANNEL_DISCONNECTED', 'Channel disconnected'), ('CHANNEL_RECONNECTING', 'Channel reconnecting'), ('CHANNEL_ERROR', 'Channel error'), ('CHANNEL_REMOVED', 'Channel removed'), ('CHANNEL_INBOUND_RECEIVED', 'Channel inbound received')], db_index=True, max_length=64),
        ),
    ]
