# Generated by Django 6.0.5 on 2026-06-22 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_ai_system_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('trigger', models.JSONField(blank=True, default=dict)),
                ('nodes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Flow',
                'verbose_name_plural': 'Flows',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'is_active'], name='automations_workspa_578b86_idx')],
            },
        ),
    ]
