# Generated by Django 6.0.5 on 2026-05-13 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('contact_type', models.CharField(choices=[('LEAD', 'Lead'), ('CLIENT', 'Cliente'), ('PARTNER', 'Parceiro')], db_index=True, default='LEAD', max_length=16)),
                ('custom_attributes', models.JSONField(blank=True, default=dict, help_text='Campos específicos do cliente (CNPJ, idade, etc.) sem alterar o schema.')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('CONTACTED', 'Contatado'), ('QUALIFIED', 'Qualificado'), ('CONVERTED', 'Convertido'), ('LOST', 'Perdido')], db_index=True, default='NEW', max_length=32)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('source', models.CharField(db_index=True, default='Manual', max_length=128)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='crm.contact')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ('-score', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'name'], name='crm_contact_workspa_ee8438_idx'),
        ),
    ]
