# Generated by Django 6.0.5 on 2026-05-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_type', models.CharField(choices=[('LEAD', 'Lead'), ('CLIENT', 'Cliente'), ('PARTNER', 'Parceiro')], db_index=True, default='LEAD', max_length=16)),
                ('custom_attributes', models.JSONField(blank=True, default=dict, help_text='Campos específicos do cliente (CNPJ, idade, etc.) sem alterar o schema.')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('CONTACTED', 'Contatado'), ('QUALIFIED', 'Qualificado'), ('CONVERTED', 'Convertido'), ('LOST', 'Perdido')], db_index=True, default='NEW', max_length=32)),
                ('score', models.IntegerField(default=0)),
                ('source', models.CharField(default='Manual', max_length=128)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='crm.contact')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ('-score', 'id'),
            },
        ),
    ]
