# Generated by Django 6.0.5 on 2026-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('workspaces', '0002_member_workspaces__workspa_02f6dd_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace'], name='crm_contact_workspa_5aa165_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['contact'], name='crm_lead_contact_497e32_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='crm_lead_status_2c1bc7_idx'),
        ),
    ]
