# Generated by Django 6.0.5 on 2026-05-18 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contact_crm_contact_workspa_5aa165_idx_and_more'),
        ('workspaces', '0003_workspaceinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='channel_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador do contato no canal (ex.: WhatsApp).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='starred',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('contacting', 'Em Contato'), ('qualified', 'Qualificado'), ('won', 'Ganho'), ('lost', 'Perdido')], db_index=True, default='new', max_length=32),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contacts', models.ManyToManyField(blank=True, related_name='organizations', to='crm.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'organização',
                'verbose_name_plural': 'organizações',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['workspace'], name='crm_organiz_workspa_3beb05_idx'), models.Index(fields=['workspace', 'name'], name='crm_organiz_workspa_245ea3_idx')],
            },
        ),
    ]
