"""
Django settings for silvertech project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
import environ
from django.core.exceptions import ImproperlyConfigured
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializa o environ e carrega as variáveis do arquivo .env (Card #034)
env = environ.Env()
if os.environ.get('READ_DOT_ENV_FILE', 'true').lower() not in {'0', 'false', 'no'}:
    environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


def required_env(name: str) -> str:
    """Le variavel obrigatoria sem expor seu conteudo em mensagens de erro."""
    value = env(name, default=None)
    if value in (None, ''):
        raise ImproperlyConfigured(f'A variavel de ambiente {name} e obrigatoria.')
    return value


DJANGO_ENV = env('DJANGO_ENV', default='production').lower()
IS_PRODUCTION = DJANGO_ENV == 'production'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = required_env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])
if IS_PRODUCTION and (not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS):
    raise ImproperlyConfigured(
        'ALLOWED_HOSTS deve ser configurado sem wildcard em producao.',
    )


# Application definition

INSTALLED_APPS = [
    'channels',
    'django_eventstream',
    # Core must precede django.contrib.admin so app template overrides can theme /admin/.
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # API, CORS e domínio
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'django_filters',
    'rest_framework_simplejwt',
    'encrypted_model_fields',
    'workspaces',
    'crm.apps.CrmConfig',
    'omnichannel',
    'tickets',
    'automations',
]

# Modelo de usuário customizado (login por e-mail, roles da plataforma).
AUTH_USER_MODEL = 'core.CustomUser'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.AuditRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'silvertech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'silvertech.wsgi.application'
ASGI_APPLICATION = 'silvertech.asgi.application'

# Channels + Redis (Card #024 — infraestrutura tempo real).
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [
                (
                    required_env('REDIS_HOST'),
                    env.int('REDIS_PORT'),
                ),
            ],
        },
    },
}

# django-eventstream — publicação multiprocesso via Redis.
EVENTSTREAM_REDIS = {
    'host': required_env('REDIS_HOST'),
    'port': env.int('REDIS_PORT'),
    'db': env.int('REDIS_DB'),
}
EVENTSTREAM_CHANNELMANAGER_CLASS = 'omnichannel.channelmanager.WorkspaceChannelManager'

# Cache Redis para endpoints pesados (analytics/dashboard).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': required_env('REDIS_CACHE_URL'),
    },
}

# Celery — broker/result backend Redis (Card #027).
CELERY_BROKER_URL = required_env('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = required_env('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL — variáveis de ambiente permitem 12-factor sem hardcode em produção.
DATABASE_URL = env('DATABASE_URL', default=None)
if DATABASE_URL:
    DATABASES = {
        'default': env.db('DATABASE_URL'),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': required_env('POSTGRES_DB'),
            'USER': required_env('POSTGRES_USER'),
            'PASSWORD': required_env('POSTGRES_PASSWORD'),
            'HOST': required_env('POSTGRES_HOST'),
            'PORT': required_env('POSTGRES_PORT'),
            'CONN_MAX_AGE': env.int('POSTGRES_CONN_MAX_AGE', default=60),
        },
    }

# Django REST Framework — autenticação JWT por padrão nas views protegidas.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/minute',
        'user': '10000/minute',
        'auth': '5/minute',
        'webhook': '120/minute',
        'ai_provider_test_connection': '5/minute',
        'ai_provider_activation': '5/minute',
        'whatsapp_channel_provisioning': '3/minute',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API Silvertech Omnichannel',
    'DESCRIPTION': 'Documentação da API do CRM Omnichannel (incluindo integração WhatsApp via Evolution API).',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Simple JWT — tempos de vida padrão para access/refresh (API stateless).
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# CORS — origens do front-end em desenvolvimento (Card #004).
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
if IS_PRODUCTION and CORS_ALLOW_ALL_ORIGINS:
    raise ImproperlyConfigured('CORS_ALLOW_ALL_ORIGINS nao pode ser True em producao.')
EVENTSTREAM_ALLOW_ORIGINS = CORS_ALLOWED_ORIGINS

# Evolution API (WhatsApp) - validacao no boot.
EVOLUTION_API_URL = env('EVOLUTION_API_URL')
# Como nao ha "default" configurado abaixo, o Django exigira essas chaves no boot.
EVOLUTION_API_KEY = env('EVOLUTION_API_KEY')
EVOLUTION_INSTANCE_NAME = env('EVOLUTION_INSTANCE_NAME')
EVOLUTION_API_TIMEOUT_SECONDS = env.int('EVOLUTION_API_TIMEOUT_SECONDS', default=30)

# Criptografia de campos sensiveis por tenant.
FIELD_ENCRYPTION_KEY = required_env('FIELD_ENCRYPTION_KEY')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sentry - monitoramento de erros e performance.
SENTRY_DSN = os.getenv('SENTRY_DSN')

if SENTRY_DSN:
    from core.sanitization import sentry_before_send

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
        ],
        traces_sample_rate=1.0,
        profiles_sample_rate=1.0,
        before_send=sentry_before_send,
    )

# django-debug-toolbar - apenas em ambiente local/debug.
if DEBUG:
    INSTALLED_APPS += [
        'debug_toolbar',
    ]
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = [
        '127.0.0.1',
        'localhost',
    ]

# Security headers / OWASP hardening.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_SSL_REDIRECT = IS_PRODUCTION
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SECURE_HSTS_SECONDS = 31536000 if IS_PRODUCTION else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION
SECURE_HSTS_PRELOAD = IS_PRODUCTION
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'
if IS_PRODUCTION:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Content Security Policy base para API, Swagger UI e front-end local.
CSP_DEFAULT_SRC = ("'none'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'")
CSP_IMG_SRC = ("'self'", 'data:')
CSP_FONT_SRC = ("'self'",)
CSP_CONNECT_SRC = ("'self'", 'http://localhost:3000', 'http://127.0.0.1:3000')
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': CSP_DEFAULT_SRC,
        'style-src': CSP_STYLE_SRC,
        'script-src': CSP_SCRIPT_SRC,
        'img-src': CSP_IMG_SRC,
        'font-src': CSP_FONT_SRC,
        'connect-src': CSP_CONNECT_SRC,
    },
}
