# Generated by Django 6.0.5 on 2026-06-22 19:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_contact_channel_id_contact_starred_lead_assigned_to_and_more'),
        ('omnichannel', '0003_conversation_is_human_handoff'),
        ('workspaces', '0003_workspaceinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em andamento'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], db_index=True, default='open', max_length=32)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='crm.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='omnichannel.conversation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'status'], name='tickets_tic_workspa_9983da_idx'), models.Index(fields=['workspace', 'due_at'], name='tickets_tic_workspa_8842df_idx'), models.Index(fields=['assigned_to', 'status'], name='tickets_tic_assigne_e36302_idx')],
            },
        ),
    ]
